name: baza
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Geolocation packages
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  geolocator: ^11.0.0
  latlong2: ^0.9.1

  # Utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State management
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_libphonenumber: ^2.2.1

  # Others
  flutter_native_splash: ^2.3.7
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/user/
    - assets/images/on_boarding_images/
    - assets/images/illustrations/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/brands/
    - assets/icons/categories/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          # width: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          # width: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          # width: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          # width: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          # width: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          # width: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          # width: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          # width: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          # width: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          # width: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          # width: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          # width: 700
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          # width: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          # width: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          # width: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          # width: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          # width: 900
          style: italic

  # see https://flutter.dev/custom-fonts/#from-packages